<a href="https://colab.research.google.com/github/anirbanghoshsbi/pandas/blob/master/diagonal_of_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# import the libraries
import numpy as np


In [0]:
#create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
matrix.diagonal()

array([1, 5, 9])

In [22]:
matrix.diagonal(offset=1) # ruturn the elements parallel to the diagonal but on the upper side

array([2, 6])

In [23]:
matrix.diagonal(offset=-1) # ruturn the elements parallel to the diagonal but on the lower side

array([4, 8])