<a href="https://colab.research.google.com/github/anirbanghoshsbi/pandas/blob/master/flatten_a_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# import the libraries
import numpy as np
# create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
#check the dimensions
print(matrix.ndim)

2


In [8]:
#flatten the matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(matrix.flatten().ndim)

1


In [14]:
a=matrix.reshape(1,-1)
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
print(a.ndim)

2


In [16]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])