<a href="https://colab.research.google.com/github/anirbanghoshsbi/pandas/blob/master/rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#  import the libraries
import numpy as np
# create the matrix
matrix = np.array([[1,1,5,6,9],[2,2,10,12,18],[3,4,7,11,13]])

In [12]:
print(matrix)

[[ 1  1  5  6  9]
 [ 2  2 10 12 18]
 [ 3  4  7 11 13]]


In [13]:
np.linalg.matrix_rank(matrix)

2